"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
[([\\(](bold bg:color_bg1 fg:color_orange)$os $username[\\)](bold bg:color_bg1 fg:color_orange)[⎯⟶](bg:color_bg1 fg:color_green))](bg:color_bg1)\
[\\(](bold bg:color_bg1 fg:color_yellow)\
$directory\
[\\)](bold bg:color_bg1 fg:color_yellow)\
[⎯⟶](bg:color_bg1 fg:color_green)\
[([\\(](bold bg:color_bg1 fg:color_aqua)$git_branch$git_status[\\)](bold bg:color_bg1 fg:color_aqua)[⎯⟶](bg:color_bg1 fg:color_green))](bg:color_bg1)\
[([\\(](bold bg:color_bg1 fg:color_blue)$c$rust$golang$nodejs$php$java$kotlin$haskell$python[\\)](bold bg:color_bg1 fg:color_blue)[⎯⟶](bg:color_bg1 fg:color_green))](bg:color_bg1)\
[([\\(](bold bg:color_bg1 fg:color_purple)$docker_context$conda[\\)](bold bg:color_bg1 fg:color_purple)[⎯⟶](bg:color_bg1 fg:color_green))](bg:color_bg1)\
[\\(](bold bg:color_bg1 fg:color_red)\
$time\
[\\)](bold bg:color_bg1 fg:color_red)\
[ ](fg:color_bg1)
$character\
"""
add_newline = true

palette = 'gram_dark'

[palettes.gram_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#99E65F'
color_orange = '#eca005'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#fce500'

[os]
disabled = false
style = "bg:color_bg1 fg:color_orange"
format = '[$symbol:OS]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = "[ {user:'$user'}]($style)"

[directory]
style = "fg:color_fg0 bg:color_bg1"
format = "[[󰈙](fg:color_yellow bg:color_bg1) {path:'$path'}]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_bg1)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_bg1)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg1"
format = '[[$symbol](fg:color_aqua bg:color_bg1)[( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[c]
symbol = " "
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[rust]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[golang]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[php]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[java]
symbol = " "
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[python]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg1)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[](fg:color_red bg:color_bg1)[ {stamp:time`$time`} ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[⟶](bold fg:color_green)'
error_symbol = '[⟶](bold fg:color_red)'
vimcmd_symbol = '[⟵](bold fg:color_green)'
vimcmd_replace_one_symbol = '[⟵](bold fg:color_purple)'
vimcmd_replace_symbol = '[⟵](bold fg:color_purple)'
vimcmd_visual_symbol = '[⟵](bold fg:color_yellow)'
